-- Cricket: tops up men's and women's T20I nations. Test/ODI teams from
-- your lists already exist (checked against what's on the site) — only
-- the much larger T20I rosters actually add anything new, since ICC T20I
-- status now covers almost every cricket-playing nation. All go into the
-- same "International" competition as everyone else, women's suffixed
-- " Women" as usual. Safe to re-run.
--
-- Colors reuse this site's existing pick for a country wherever one
-- exists elsewhere; brand-new/smaller cricket nations are flag-based
-- best guesses.

insert into teams (slug, competition_slug, name, primary_color, secondary_color) values
  ('switzerland','international','Switzerland','#D52B1E','#FFFFFF'),
  ('cook-islands','international','Cook Islands','#00247D','#CE1126'),
  ('rwanda','international','Rwanda','#20603D','#FAD201'),
  ('botswana','international','Botswana','#75AADB','#000000'),
  ('malawi','international','Malawi','#000000','#CE1126'),
  ('isle-of-man','international','Isle of Man','#CE1126','#FFFFFF'),
  ('philippines','international','Philippines','#0038A8','#CE1126'),
  ('ghana','international','Ghana','#006B3F','#FCD116'),
  ('bahamas','international','Bahamas','#00778B','#FFC72C'),
  ('cambodia','international','Cambodia','#032EA1','#E00025'),
  ('indonesia','international','Indonesia','#CE1126','#FFFFFF'),
  ('zambia','international','Zambia','#198A00','#EF7D00'),
  ('czechia','international','Czechia','#D7141A','#11457E'),
  ('malta','international','Malta','#CE1126','#FFFFFF'),
  ('vanuatu','international','Vanuatu','#D21034','#FDCE12'),
  ('eswatini','international','Eswatini','#0018A8','#FFD200'),
  ('hungary','international','Hungary','#CD2A3E','#436F4D'),
  ('panama','international','Panama','#DA121A','#072357'),
  ('estonia','international','Estonia','#0072CE','#000000'),
  ('cameroon','international','Cameroon','#007A5E','#CE1126'),
  ('bhutan','international','Bhutan','#FF4E12','#FFC726'),
  ('belize','international','Belize','#003F87','#CE1126'),
  ('mexico','international','Mexico','#006847','#CE1126'),
  ('korea','international','Korea','#003478','#CD2E3A'),
  ('luxembourg','international','Luxembourg','#ED2939','#00A1DE'),
  ('brazil','international','Brazil','#009739','#FEDD00'),
  ('gibraltar','international','Gibraltar','#E8112D','#FFFFFF'),
  ('mozambique','international','Mozambique','#007168','#CE1126'),
  ('israel','international','Israel','#0038B8','#FFFFFF'),
  ('maldives','international','Maldives','#D21034','#007E3A'),
  ('sierra-leone','international','Sierra Leone','#1EB53A','#0072C6'),
  ('suriname','international','Suriname','#377E3F','#B40A2D'),
  ('bulgaria','international','Bulgaria','#FFFFFF','#00966E'),
  ('croatia','international','Croatia','#FF0000','#FFFFFF'),
  ('seychelles','international','Seychelles','#003F87','#FCD116'),
  ('lesotho','international','Lesotho','#00209F','#009543'),
  ('serbia','international','Serbia','#C6363C','#0C4076'),
  ('turkiye','international','Türkiye','#E30A17','#FFFFFF'),
  ('china','international','China','#DE2910','#FFDE00'),
  ('fiji','international','Fiji','#71C5E8','#FFFFFF'),
  ('timor-leste','international','Timor-Leste','#DC241F','#FFC726'),
  ('ivory-coast','international','Ivory Coast','#FF8200','#009E60'),
  ('mongolia','international','Mongolia','#C4272F','#015197'),
  ('st-helena','international','St Helena','#00247D','#CE1126'),
  ('slovenia','international','Slovenia','#005DA4','#FFFFFF'),
  ('myanmar','international','Myanmar','#FECB00','#34B233'),
  ('mali','international','Mali','#14B53A','#FCD116'),
  ('greece','international','Greece','#0D5EAF','#FFFFFF'),
  ('costa-rica','international','Costa Rica','#002B7F','#CE1126')
on conflict (competition_slug, slug) do nothing;

insert into teams (slug, competition_slug, name, primary_color, secondary_color) values
  ('kenya-women','international','Kenya Women','#006400','#CE1126'),
  ('jersey-women','international','Jersey Women','#CE1126','#FFFFFF'),
  ('spain-women','international','Spain Women','#C60B1E','#FFC400'),
  ('sweden-women','international','Sweden Women','#006AA7','#FECC02'),
  ('oman-women','international','Oman Women','#DB161B','#008751'),
  ('china-women','international','China Women','#DE2910','#FFDE00'),
  ('cyprus-women','international','Cyprus Women','#FFFFFF','#D57800'),
  ('isle-of-man-women','international','Isle of Man Women','#CE1126','#FFFFFF'),
  ('japan-women','international','Japan Women','#BC002D','#FFFFFF'),
  ('turkiye-women','international','Türkiye Women','#E30A17','#FFFFFF'),
  ('switzerland-women','international','Switzerland Women','#D52B1E','#FFFFFF'),
  ('canada-women','international','Canada Women','#FF0000','#FFFFFF'),
  ('myanmar-women','international','Myanmar Women','#FECB00','#34B233'),
  ('denmark-women','international','Denmark Women','#C60C30','#FFFFFF'),
  ('sierra-leone-women','international','Sierra Leone Women','#1EB53A','#0072C6'),
  ('bhutan-women','international','Bhutan Women','#FF4E12','#FFC726'),
  ('argentina-women','international','Argentina Women','#75AADB','#FFFFFF'),
  ('france-women','international','France Women','#002654','#ED2939'),
  ('botswana-women','international','Botswana Women','#75AADB','#000000'),
  ('gibraltar-women','international','Gibraltar Women','#E8112D','#FFFFFF'),
  ('kuwait-women','international','Kuwait Women','#007A3D','#CE1126'),
  ('croatia-women','international','Croatia Women','#FF0000','#FFFFFF'),
  ('samoa-women','international','Samoa Women','#002B7F','#CE1126'),
  ('austria-women','international','Austria Women','#ED2939','#FFFFFF'),
  ('portugal-women','international','Portugal Women','#FF0000','#046A38'),
  ('romania-women','international','Romania Women','#FCD116','#002B7F'),
  ('guernsey-women','international','Guernsey Women','#CE1126','#FFFFFF'),
  ('norway-women','international','Norway Women','#BA0C2F','#00205B'),
  ('malawi-women','international','Malawi Women','#000000','#CE1126'),
  ('fiji-women','international','Fiji Women','#71C5E8','#FFFFFF'),
  ('serbia-women','international','Serbia Women','#C6363C','#0C4076'),
  ('czechia-women','international','Czechia Women','#D7141A','#11457E'),
  ('greece-women','international','Greece Women','#0D5EAF','#FFFFFF'),
  ('estonia-women','international','Estonia Women','#0072CE','#000000'),
  ('qatar-women','international','Qatar Women','#8D1B3D','#FFFFFF'),
  ('finland-women','international','Finland Women','#002F6C','#FFFFFF'),
  ('mozambique-women','international','Mozambique Women','#007168','#CE1126'),
  ('malta-women','international','Malta Women','#CE1126','#FFFFFF'),
  ('cameroon-women','international','Cameroon Women','#007A5E','#CE1126'),
  ('luxembourg-women','international','Luxembourg Women','#ED2939','#00A1DE'),
  ('lesotho-women','international','Lesotho Women','#00209F','#009543'),
  ('mongolia-women','international','Mongolia Women','#C4272F','#015197'),
  ('philippines-women','international','Philippines Women','#0038A8','#CE1126'),
  ('singapore-women','international','Singapore Women','#EF3340','#FFFFFF'),
  ('eswatini-women','international','Eswatini Women','#0018A8','#FFD200'),
  ('saudi-arabia-women','international','Saudi Arabia Women','#006C35','#FFFFFF'),
  ('cook-islands-women','international','Cook Islands Women','#00247D','#CE1126'),
  ('bulgaria-women','international','Bulgaria Women','#FFFFFF','#00966E'),
  ('belgium-women','international','Belgium Women','#000000','#FDDA24'),
  ('bahrain-women','international','Bahrain Women','#CE1126','#FFFFFF')
on conflict (competition_slug, slug) do nothing;
