-- Adds International (Men) and International (Women) competitions under
-- the new Field Hockey sport, with your full team lists. Colours are
-- flag-based for every country — real facts, not guesses, though a
-- handful of the least common flags (Eswatini, Solomon Islands, a few
-- others) are my best approximation of a multi-colour flag reduced to
-- two swatches. New Zealand uses black/white (the Black Sticks' actual
-- kit identity) rather than its flag's blue/red, same logic already
-- used elsewhere on the site for a team whose real playing colours
-- differ from its national flag. Safe to re-run.

insert into competitions (slug, sport_slug, name, tier) values
  ('international-field-hockey-men','field-hockey','International (Men)','top'),
  ('international-field-hockey-women','field-hockey','International (Women)','top')
on conflict (slug) do nothing;

-- ============ Field Hockey — International (Men) ============
insert into teams (slug, competition_slug, name, primary_color, secondary_color) values
  ('germany','international-field-hockey-men','Germany','#000000','#DD0000'),
  ('belgium','international-field-hockey-men','Belgium','#000000','#FDDA24'),
  ('australia','international-field-hockey-men','Australia','#FFD700','#00843D'),
  ('argentina','international-field-hockey-men','Argentina','#75AADB','#FFFFFF'),
  ('netherlands','international-field-hockey-men','Netherlands','#FF6C00','#FFFFFF'),
  ('spain','international-field-hockey-men','Spain','#C60B1E','#FFC400'),
  ('england','international-field-hockey-men','England','#FFFFFF','#CE1124'),
  ('india','international-field-hockey-men','India','#FF9933','#138808'),
  ('new-zealand','international-field-hockey-men','New Zealand','#000000','#FFFFFF'),
  ('france','international-field-hockey-men','France','#002654','#FFFFFF'),
  ('ireland','international-field-hockey-men','Ireland','#169B62','#FF883E'),
  ('pakistan','international-field-hockey-men','Pakistan','#01411C','#FFFFFF'),
  ('south-africa','international-field-hockey-men','South Africa','#007A4D','#FFB612'),
  ('scotland','international-field-hockey-men','Scotland','#005EB8','#FFFFFF'),
  ('malaysia','international-field-hockey-men','Malaysia','#010066','#FFCC00'),
  ('egypt','international-field-hockey-men','Egypt','#CE1126','#000000'),
  ('japan','international-field-hockey-men','Japan','#BC002D','#FFFFFF'),
  ('wales','international-field-hockey-men','Wales','#C8102E','#00843D'),
  ('canada','international-field-hockey-men','Canada','#FF0000','#FFFFFF'),
  ('china','international-field-hockey-men','China','#DE2910','#FFDE00'),
  ('poland','international-field-hockey-men','Poland','#DC143C','#FFFFFF'),
  ('austria','international-field-hockey-men','Austria','#ED2939','#FFFFFF'),
  ('south-korea','international-field-hockey-men','South Korea','#C60C30','#003478'),
  ('chile','international-field-hockey-men','Chile','#D52B1E','#0033A0'),
  ('oman','international-field-hockey-men','Oman','#DB161B','#008000'),
  ('italy','international-field-hockey-men','Italy','#0F4C81','#FFFFFF'),
  ('united-states','international-field-hockey-men','United States','#002868','#BF0D3E'),
  ('bangladesh','international-field-hockey-men','Bangladesh','#006A4E','#F42A41'),
  ('russia','international-field-hockey-men','Russia','#0033A0','#D52B1E'),
  ('czech-republic','international-field-hockey-men','Czech Republic','#D7141A','#11457E'),
  ('mexico','international-field-hockey-men','Mexico','#006847','#CE1126'),
  ('ukraine','international-field-hockey-men','Ukraine','#005BBB','#FFD500'),
  ('ghana','international-field-hockey-men','Ghana','#CE1126','#FCD116'),
  ('brazil','international-field-hockey-men','Brazil','#FFDF00','#009739'),
  ('nigeria','international-field-hockey-men','Nigeria','#008751','#FFFFFF'),
  ('trinidad-and-tobago','international-field-hockey-men','Trinidad and Tobago','#CE1126','#000000'),
  ('sri-lanka','international-field-hockey-men','Sri Lanka','#FFB700','#8D153A'),
  ('switzerland','international-field-hockey-men','Switzerland','#FF0000','#FFFFFF'),
  ('belarus','international-field-hockey-men','Belarus','#C8102E','#00A651'),
  ('venezuela','international-field-hockey-men','Venezuela','#FCD116','#00247D'),
  ('croatia','international-field-hockey-men','Croatia','#FF0000','#171796'),
  ('dominican-republic','international-field-hockey-men','Dominican Republic','#002D62','#CE1126'),
  ('turkey','international-field-hockey-men','Turkey','#E30A17','#FFFFFF'),
  ('finland','international-field-hockey-men','Finland','#003580','#FFFFFF'),
  ('uzbekistan','international-field-hockey-men','Uzbekistan','#0099B5','#1EB53A'),
  ('chinese-taipei','international-field-hockey-men','Chinese Taipei','#000095','#FE0000'),
  ('thailand','international-field-hockey-men','Thailand','#A51931','#2D2A4A'),
  ('kenya','international-field-hockey-men','Kenya','#006400','#CE1126'),
  ('gibraltar','international-field-hockey-men','Gibraltar','#CE1126','#FFFFFF'),
  ('singapore','international-field-hockey-men','Singapore','#ED2939','#FFFFFF'),
  ('hong-kong','international-field-hockey-men','Hong Kong','#DE2910','#FFFFFF'),
  ('lithuania','international-field-hockey-men','Lithuania','#FDB913','#006A44'),
  ('slovakia','international-field-hockey-men','Slovakia','#0B4EA2','#EE1C25'),
  ('barbados','international-field-hockey-men','Barbados','#00267F','#FFC726'),
  ('uruguay','international-field-hockey-men','Uruguay','#0038A8','#FFFFFF'),
  ('papua-new-guinea','international-field-hockey-men','Papua New Guinea','#CE1126','#000000'),
  ('indonesia','international-field-hockey-men','Indonesia','#CE1126','#FFFFFF'),
  ('portugal','international-field-hockey-men','Portugal','#FF0000','#046A38'),
  ('cyprus','international-field-hockey-men','Cyprus','#D57800','#FFFFFF'),
  ('puerto-rico','international-field-hockey-men','Puerto Rico','#0044FF','#CE1126'),
  ('solomon-islands','international-field-hockey-men','Solomon Islands','#0072CE','#FCD116'),
  ('guatemala','international-field-hockey-men','Guatemala','#4997D0','#FFFFFF'),
  ('tonga','international-field-hockey-men','Tonga','#C10000','#FFFFFF'),
  ('vanuatu','international-field-hockey-men','Vanuatu','#D21034','#009543'),
  ('jamaica','international-field-hockey-men','Jamaica','#009B3A','#FED100'),
  ('afghanistan','international-field-hockey-men','Afghanistan','#000000','#D32011'),
  ('brunei','international-field-hockey-men','Brunei','#FFCC00','#000000'),
  ('fiji','international-field-hockey-men','Fiji','#71C5E8','#FFFFFF'),
  ('namibia','international-field-hockey-men','Namibia','#003580','#009543'),
  ('myanmar','international-field-hockey-men','Myanmar','#FECB00','#34B233'),
  ('kazakhstan','international-field-hockey-men','Kazakhstan','#00AFCA','#FEC50C'),
  ('peru','international-field-hockey-men','Peru','#D91023','#FFFFFF'),
  ('samoa','international-field-hockey-men','Samoa','#CE1126','#002B7F'),
  ('norway','international-field-hockey-men','Norway','#BA0C2F','#00205B'),
  ('nepal','international-field-hockey-men','Nepal','#DC143C','#003893'),
  ('vietnam','international-field-hockey-men','Vietnam','#DA251D','#FFFF00'),
  ('panama','international-field-hockey-men','Panama','#DA121A','#072357'),
  ('qatar','international-field-hockey-men','Qatar','#8A1538','#FFFFFF'),
  ('malta','international-field-hockey-men','Malta','#CF142B','#FFFFFF'),
  ('slovenia','international-field-hockey-men','Slovenia','#FFFFFF','#005DA4'),
  ('costa-rica','international-field-hockey-men','Costa Rica','#002B7F','#CE1126'),
  ('bolivia','international-field-hockey-men','Bolivia','#D52B1E','#FCD116'),
  ('macau','international-field-hockey-men','Macau','#00785E','#FFFFFF'),
  ('guyana','international-field-hockey-men','Guyana','#009E49','#FCD116'),
  ('hungary','international-field-hockey-men','Hungary','#CD2A3E','#436F4D'),
  ('ecuador','international-field-hockey-men','Ecuador','#FFD100','#0033A0'),
  ('uganda','international-field-hockey-men','Uganda','#000000','#FCDC04'),
  ('zimbabwe','international-field-hockey-men','Zimbabwe','#006400','#FFD200'),
  ('zambia','international-field-hockey-men','Zambia','#198A00','#DE2010'),
  ('paraguay','international-field-hockey-men','Paraguay','#D52B1E','#0038A8'),
  ('iran','international-field-hockey-men','Iran','#239F40','#DA0000'),
  ('bermuda','international-field-hockey-men','Bermuda','#00247D','#C8102E'),
  ('el-salvador','international-field-hockey-men','El Salvador','#0047AB','#FFFFFF'),
  ('serbia','international-field-hockey-men','Serbia','#C6363C','#0C4076'),
  ('malawi','international-field-hockey-men','Malawi','#000000','#CE1126'),
  ('cambodia','international-field-hockey-men','Cambodia','#032EA1','#E00025'),
  ('tajikistan','international-field-hockey-men','Tajikistan','#CC0000','#006600'),
  ('kyrgyzstan','international-field-hockey-men','Kyrgyzstan','#E8112D','#FFEF00'),
  ('luxembourg','international-field-hockey-men','Luxembourg','#00A1DE','#ED2939'),
  ('eswatini','international-field-hockey-men','Eswatini','#002F87','#FFD100'),
  ('bulgaria','international-field-hockey-men','Bulgaria','#00966E','#D62612'),
  ('greece','international-field-hockey-men','Greece','#0D5EAF','#FFFFFF'),
  ('morocco','international-field-hockey-men','Morocco','#C1272D','#006233')
on conflict (competition_slug, slug) do nothing;

-- ============ Field Hockey — International (Women) ============
insert into teams (slug, competition_slug, name, primary_color, secondary_color) values
  ('netherlands','international-field-hockey-women','Netherlands','#FF6C00','#FFFFFF'),
  ('argentina','international-field-hockey-women','Argentina','#75AADB','#FFFFFF'),
  ('belgium','international-field-hockey-women','Belgium','#000000','#FDDA24'),
  ('china','international-field-hockey-women','China','#DE2910','#FFDE00'),
  ('spain','international-field-hockey-women','Spain','#C60B1E','#FFC400'),
  ('germany','international-field-hockey-women','Germany','#000000','#DD0000'),
  ('england','international-field-hockey-women','England','#FFFFFF','#CE1124'),
  ('india','international-field-hockey-women','India','#FF9933','#138808'),
  ('australia','international-field-hockey-women','Australia','#FFD700','#00843D'),
  ('united-states','international-field-hockey-women','United States','#002868','#BF0D3E'),
  ('japan','international-field-hockey-women','Japan','#BC002D','#FFFFFF'),
  ('new-zealand','international-field-hockey-women','New Zealand','#000000','#FFFFFF'),
  ('ireland','international-field-hockey-women','Ireland','#169B62','#FF883E'),
  ('scotland','international-field-hockey-women','Scotland','#005EB8','#FFFFFF'),
  ('chile','international-field-hockey-women','Chile','#D52B1E','#0033A0'),
  ('france','international-field-hockey-women','France','#002654','#FFFFFF'),
  ('south-korea','international-field-hockey-women','South Korea','#C60C30','#003478'),
  ('south-africa','international-field-hockey-women','South Africa','#007A4D','#FFB612'),
  ('italy','international-field-hockey-women','Italy','#0F4C81','#FFFFFF'),
  ('uruguay','international-field-hockey-women','Uruguay','#0038A8','#FFFFFF'),
  ('malaysia','international-field-hockey-women','Malaysia','#010066','#FFCC00'),
  ('belarus','international-field-hockey-women','Belarus','#C8102E','#00A651'),
  ('russia','international-field-hockey-women','Russia','#0033A0','#D52B1E'),
  ('wales','international-field-hockey-women','Wales','#C8102E','#00843D'),
  ('poland','international-field-hockey-women','Poland','#DC143C','#FFFFFF'),
  ('canada','international-field-hockey-women','Canada','#FF0000','#FFFFFF'),
  ('thailand','international-field-hockey-women','Thailand','#A51931','#2D2A4A'),
  ('ukraine','international-field-hockey-women','Ukraine','#005BBB','#FFD500'),
  ('czech-republic','international-field-hockey-women','Czech Republic','#D7141A','#11457E'),
  ('mexico','international-field-hockey-women','Mexico','#006847','#CE1126'),
  ('austria','international-field-hockey-women','Austria','#ED2939','#FFFFFF'),
  ('kenya','international-field-hockey-women','Kenya','#006400','#CE1126'),
  ('ghana','international-field-hockey-women','Ghana','#CE1126','#FCD116'),
  ('hong-kong','international-field-hockey-women','Hong Kong','#DE2910','#FFFFFF'),
  ('switzerland','international-field-hockey-women','Switzerland','#FF0000','#FFFFFF'),
  ('turkey','international-field-hockey-women','Turkey','#E30A17','#FFFFFF'),
  ('cuba','international-field-hockey-women','Cuba','#002A8F','#CF142B'),
  ('singapore','international-field-hockey-women','Singapore','#ED2939','#FFFFFF'),
  ('nigeria','international-field-hockey-women','Nigeria','#008751','#FFFFFF'),
  ('kazakhstan','international-field-hockey-women','Kazakhstan','#00AFCA','#FEC50C'),
  ('guatemala','international-field-hockey-women','Guatemala','#4997D0','#FFFFFF'),
  ('chinese-taipei','international-field-hockey-women','Chinese Taipei','#000095','#FE0000'),
  ('peru','international-field-hockey-women','Peru','#D91023','#FFFFFF'),
  ('paraguay','international-field-hockey-women','Paraguay','#D52B1E','#0038A8'),
  ('fiji','international-field-hockey-women','Fiji','#71C5E8','#FFFFFF'),
  ('indonesia','international-field-hockey-women','Indonesia','#CE1126','#FFFFFF'),
  ('papua-new-guinea','international-field-hockey-women','Papua New Guinea','#CE1126','#000000'),
  ('barbados','international-field-hockey-women','Barbados','#00267F','#FFC726'),
  ('dominican-republic','international-field-hockey-women','Dominican Republic','#002D62','#CE1126'),
  ('solomon-islands','international-field-hockey-women','Solomon Islands','#0072CE','#FCD116'),
  ('lithuania','international-field-hockey-women','Lithuania','#FDB913','#006A44'),
  ('namibia','international-field-hockey-women','Namibia','#003580','#009543'),
  ('trinidad-and-tobago','international-field-hockey-women','Trinidad and Tobago','#CE1126','#000000'),
  ('tonga','international-field-hockey-women','Tonga','#C10000','#FFFFFF'),
  ('hungary','international-field-hockey-women','Hungary','#CD2A3E','#436F4D'),
  ('pakistan','international-field-hockey-women','Pakistan','#01411C','#FFFFFF'),
  ('puerto-rico','international-field-hockey-women','Puerto Rico','#0044FF','#CE1126'),
  ('slovenia','international-field-hockey-women','Slovenia','#FFFFFF','#005DA4'),
  ('bolivia','international-field-hockey-women','Bolivia','#D52B1E','#FCD116'),
  ('panama','international-field-hockey-women','Panama','#DA121A','#072357'),
  ('zimbabwe','international-field-hockey-women','Zimbabwe','#006400','#FFD200'),
  ('guyana','international-field-hockey-women','Guyana','#009E49','#FCD116'),
  ('samoa','international-field-hockey-women','Samoa','#CE1126','#002B7F'),
  ('vanuatu','international-field-hockey-women','Vanuatu','#D21034','#009543'),
  ('uzbekistan','international-field-hockey-women','Uzbekistan','#0099B5','#1EB53A'),
  ('egypt','international-field-hockey-women','Egypt','#CE1126','#000000'),
  ('brunei','international-field-hockey-women','Brunei','#FFCC00','#000000'),
  ('croatia','international-field-hockey-women','Croatia','#FF0000','#171796'),
  ('brazil','international-field-hockey-women','Brazil','#FFDF00','#009739'),
  ('sri-lanka','international-field-hockey-women','Sri Lanka','#FFB700','#8D153A'),
  ('slovakia','international-field-hockey-women','Slovakia','#0B4EA2','#EE1C25'),
  ('bermuda','international-field-hockey-women','Bermuda','#00247D','#C8102E'),
  ('jamaica','international-field-hockey-women','Jamaica','#009B3A','#FED100'),
  ('portugal','international-field-hockey-women','Portugal','#FF0000','#046A38'),
  ('cambodia','international-field-hockey-women','Cambodia','#032EA1','#E00025'),
  ('zambia','international-field-hockey-women','Zambia','#198A00','#DE2010'),
  ('costa-rica','international-field-hockey-women','Costa Rica','#002B7F','#CE1126'),
  ('uganda','international-field-hockey-women','Uganda','#000000','#FCDC04'),
  ('malawi','international-field-hockey-women','Malawi','#000000','#CE1126'),
  ('venezuela','international-field-hockey-women','Venezuela','#FCD116','#00247D'),
  ('gibraltar','international-field-hockey-women','Gibraltar','#CE1126','#FFFFFF'),
  ('tajikistan','international-field-hockey-women','Tajikistan','#CC0000','#006600'),
  ('luxembourg','international-field-hockey-women','Luxembourg','#00A1DE','#ED2939'),
  ('eswatini','international-field-hockey-women','Eswatini','#002F87','#FFD100'),
  ('bangladesh','international-field-hockey-women','Bangladesh','#006A4E','#F42A41'),
  ('kyrgyzstan','international-field-hockey-women','Kyrgyzstan','#E8112D','#FFEF00'),
  ('morocco','international-field-hockey-women','Morocco','#C1272D','#006233'),
  ('finland','international-field-hockey-women','Finland','#003580','#FFFFFF')
on conflict (competition_slug, slug) do nothing;
