-- Adds the International (Men) competition and every men's national team
-- from your list (futsal, beach soccer, and women's national teams
-- excluded — those are handled separately). Slug is "international-men"
-- rather than "international" since that slug is already used by
-- cricket's International competition.
--
-- Colours: well-known football nations use their actual kit colours;
-- lesser-known ones fall back to their flag's colours as a reasonable
-- placeholder swatch (only ever visible until a real logo is uploaded) —
-- flag anything that looks wrong, easy fix either way.
--
-- Slugs for "Türkiye" and "São Tomé and Príncipe" were generated with the
-- app's own slugify() function so a later upload for either won't create
-- a duplicate team.

insert into competitions (slug, sport_slug, name, tier) values
  ('international-men','football','International (Men)','top')
on conflict (slug) do nothing;

insert into teams (slug, competition_slug, name, primary_color, secondary_color) values
  ('albania','international-men','Albania','#E41E20','#000000'),
  ('andorra','international-men','Andorra','#0018A8','#FEDF00'),
  ('angola','international-men','Angola','#CE1126','#000000'),
  ('antigua-and-barbuda','international-men','Antigua and Barbuda','#CE1126','#002B7F'),
  ('argentina','international-men','Argentina','#75AADB','#FFFFFF'),
  ('austria','international-men','Austria','#ED2939','#FFFFFF'),
  ('bangladesh','international-men','Bangladesh','#006A4E','#F42A41'),
  ('belarus','international-men','Belarus','#D22730','#007A3D'),
  ('belgium','international-men','Belgium','#ED2939','#000000'),
  ('bermuda','international-men','Bermuda','#C8102E','#00247D'),
  ('bolivia','international-men','Bolivia','#007934','#FFB612'),
  ('botswana','international-men','Botswana','#75AADB','#000000'),
  ('brazil','international-men','Brazil','#FFDF00','#009739'),
  ('burkina-faso','international-men','Burkina Faso','#EF2B2D','#009739'),
  ('burundi','international-men','Burundi','#CE1126','#1EB53A'),
  ('cameroon','international-men','Cameroon','#009739','#FCD116'),
  ('canada','international-men','Canada','#FF0000','#FFFFFF'),
  ('cape-verde','international-men','Cape Verde','#003893','#CF2027'),
  ('cayman-islands','international-men','Cayman Islands','#041E42','#FFFFFF'),
  ('central-african-republic','international-men','Central African Republic','#003082','#FFCE00'),
  ('chad','international-men','Chad','#002664','#FECB00'),
  ('chile','international-men','Chile','#D52B1E','#FFFFFF'),
  ('china','international-men','China','#DE2910','#FFDE00'),
  ('chinese-taipei','international-men','Chinese Taipei','#000095','#FFFFFF'),
  ('colombia','international-men','Colombia','#FCD116','#003893'),
  ('cook-islands','international-men','Cook Islands','#00247D','#FFFFFF'),
  ('costa-rica','international-men','Costa Rica','#CE1126','#002B7F'),
  ('croatia','international-men','Croatia','#FF0000','#FFFFFF'),
  ('cyprus','international-men','Cyprus','#FFFFFF','#D57800'),
  ('czech-republic','international-men','Czech Republic','#D7141A','#11457E'),
  ('denmark','international-men','Denmark','#C60C30','#FFFFFF'),
  ('dominica','international-men','Dominica','#006B3F','#D51B1B'),
  ('dominican-republic','international-men','Dominican Republic','#002D62','#CE1126'),
  ('ecuador','international-men','Ecuador','#FFD100','#034EA2'),
  ('england','international-men','England','#FFFFFF','#CF081F'),
  ('england-c','international-men','England C','#FFFFFF','#1B1B1B'),
  ('equatorial-guinea','international-men','Equatorial Guinea','#3A7728','#0073CF'),
  ('eswatini','international-men','Eswatini','#0018A8','#FFD100'),
  ('faroe-islands','international-men','Faroe Islands','#C8102E','#0093DD'),
  ('fiji','international-men','Fiji','#71C5E8','#FFFFFF'),
  ('france','international-men','France','#002654','#FFFFFF'),
  ('french-guiana','international-men','French Guiana','#009739','#FCD116'),
  ('gabon','international-men','Gabon','#009639','#FCD116'),
  ('germany','international-men','Germany','#FFFFFF','#000000'),
  ('gibraltar','international-men','Gibraltar','#E8112D','#FFFFFF'),
  ('greece','international-men','Greece','#0D5EAF','#FFFFFF'),
  ('grenada','international-men','Grenada','#CE1126','#FCD116'),
  ('guadeloupe','international-men','Guadeloupe','#000000','#FCD116'),
  ('guam','international-men','Guam','#002868','#BF0D3E'),
  ('guinea','international-men','Guinea','#CE1126','#FCD116'),
  ('guyana','international-men','Guyana','#009E49','#FCD116'),
  ('honduras','international-men','Honduras','#0073CF','#FFFFFF'),
  ('hong-kong','international-men','Hong Kong','#DE2910','#FFFFFF'),
  ('hungary','international-men','Hungary','#CD2A3E','#436F4D'),
  ('iceland','international-men','Iceland','#003897','#D72828'),
  ('india','international-men','India','#0033A0','#FF671F'),
  ('indonesia','international-men','Indonesia','#FF0000','#FFFFFF'),
  ('iraq','international-men','Iraq','#CE1126','#000000'),
  ('ireland','international-men','Ireland','#169B62','#FFFFFF'),
  ('italy','international-men','Italy','#0F4C81','#FFFFFF'),
  ('jamaica','international-men','Jamaica','#FED100','#009B3A'),
  ('kosovo','international-men','Kosovo','#0F4C9C','#FFCE00'),
  ('kuwait','international-men','Kuwait','#007A3D','#CE1126'),
  ('laos','international-men','Laos','#CE1126','#002868'),
  ('latvia','international-men','Latvia','#9E3039','#FFFFFF'),
  ('lebanon','international-men','Lebanon','#ED1C24','#00A651'),
  ('liberia','international-men','Liberia','#BF0A30','#002868'),
  ('libya','international-men','Libya','#000000','#239E46'),
  ('liechtenstein','international-men','Liechtenstein','#002B7F','#CE1126'),
  ('lithuania','international-men','Lithuania','#FDB913','#006A44'),
  ('luxembourg','international-men','Luxembourg','#ED2939','#00A1DE'),
  ('macau','international-men','Macau','#00A650','#FFFFFF'),
  ('madagascar','international-men','Madagascar','#FFFFFF','#007E3A'),
  ('mali','international-men','Mali','#14B53A','#FCD116'),
  ('mauritania','international-men','Mauritania','#00A95C','#FFC400'),
  ('mexico','international-men','Mexico','#006847','#FFFFFF'),
  ('montenegro','international-men','Montenegro','#C40308','#D4AF37'),
  ('montserrat','international-men','Montserrat','#00247D','#FFFFFF'),
  ('namibia','international-men','Namibia','#003580','#FFCE00'),
  ('nepal','international-men','Nepal','#DC143C','#003893'),
  ('netherlands','international-men','Netherlands','#FF6C00','#FFFFFF'),
  ('new-zealand','international-men','New Zealand','#FFFFFF','#000000'),
  ('nicaragua','international-men','Nicaragua','#0067C6','#FFFFFF'),
  ('niger','international-men','Niger','#E05206','#0DB02B'),
  ('nigeria','international-men','Nigeria','#008751','#FFFFFF'),
  ('north-korea','international-men','North Korea','#024FA2','#ED1C27'),
  ('northern-ireland','international-men','Northern Ireland','#009A44','#FFFFFF'),
  ('norway','international-men','Norway','#BA0C2F','#00205B'),
  ('oman','international-men','Oman','#DB161B','#008751'),
  ('palestine','international-men','Palestine','#FFFFFF','#000000'),
  ('panama','international-men','Panama','#DA121A','#072357'),
  ('papua-new-guinea','international-men','Papua New Guinea','#CE1126','#000000'),
  ('paraguay','international-men','Paraguay','#D52B1E','#0038A8'),
  ('peru','international-men','Peru','#D91023','#FFFFFF'),
  ('philippines','international-men','Philippines','#0038A8','#CE1126'),
  ('poland','international-men','Poland','#DC143C','#FFFFFF'),
  ('portugal','international-men','Portugal','#FF0000','#046A38'),
  ('puerto-rico','international-men','Puerto Rico','#DA121A','#0033A0'),
  ('qatar','international-men','Qatar','#8D1B3D','#FFFFFF'),
  ('russia','international-men','Russia','#FFFFFF','#D52B1E'),
  ('san-marino','international-men','San Marino','#5EB6E4','#FFFFFF'),
  ('s-o-tom-and-pr-ncipe','international-men','São Tomé and Príncipe','#12AD2B','#FFCE00'),
  ('saudi-arabia','international-men','Saudi Arabia','#006C35','#FFFFFF'),
  ('scotland','international-men','Scotland','#00205B','#FFFFFF'),
  ('serbia','international-men','Serbia','#C6363C','#0C4076'),
  ('singapore','international-men','Singapore','#EF3340','#FFFFFF'),
  ('sint-maarten','international-men','Sint Maarten','#00247D','#CE1126'),
  ('slovakia','international-men','Slovakia','#0B4EA2','#EE1C25'),
  ('slovenia','international-men','Slovenia','#005DA4','#FFFFFF'),
  ('solomon-islands','international-men','Solomon Islands','#0051BA','#FCD116'),
  ('somalia','international-men','Somalia','#4189DD','#FFFFFF'),
  ('south-korea','international-men','South Korea','#C60C30','#0047A0'),
  ('spain','international-men','Spain','#C60B1E','#FFC400'),
  ('sweden','international-men','Sweden','#006AA7','#FECC02'),
  ('switzerland','international-men','Switzerland','#D52B1E','#FFFFFF'),
  ('syria','international-men','Syria','#CE1126','#000000'),
  ('tajikistan','international-men','Tajikistan','#CC0000','#006847'),
  ('togo','international-men','Togo','#006A4E','#FFCE00'),
  ('tonga','international-men','Tonga','#C10000','#FFFFFF'),
  ('trinidad-and-tobago','international-men','Trinidad and Tobago','#CE1126','#000000'),
  ('tunisia','international-men','Tunisia','#E70013','#FFFFFF'),
  ('t-rkiye','international-men','Türkiye','#E30A17','#FFFFFF'),
  ('turks-and-caicos-islands','international-men','Turks and Caicos Islands','#00247D','#FFFFFF'),
  ('ukraine','international-men','Ukraine','#005BBB','#FFD500'),
  ('uruguay','international-men','Uruguay','#6CACE4','#FFFFFF'),
  ('usa','international-men','USA','#002868','#BF0D3E'),
  ('uzbekistan','international-men','Uzbekistan','#0099B5','#1EB53A'),
  ('vanuatu','international-men','Vanuatu','#CE1126','#009543'),
  ('venezuela','international-men','Venezuela','#7B1113','#FFCC00'),
  ('wales','international-men','Wales','#C8102E','#FFFFFF'),
  ('yemen','international-men','Yemen','#CE1126','#000000'),
  ('zambia','international-men','Zambia','#198A00','#EF7D00')
on conflict (competition_slug, slug) do update
  set primary_color = excluded.primary_color, secondary_color = excluded.secondary_color;
