-- Expands rugby league's International (Men) competition to your fuller
-- list of 74 nations (the 22 already there are included again here too —
-- harmless, on conflict just refreshes their colours to match). Colours
-- reuse the same national palette used for these countries elsewhere on
-- the site (football/rugby union/basketball) for consistency. Safe to
-- re-run.

insert into teams (slug, competition_slug, name, primary_color, secondary_color) values
  ('afghanistan','international-rugby-league-men','Afghanistan','#0033A0','#FFFFFF'),
  ('albania','international-rugby-league-men','Albania','#E41E20','#000000'),
  ('argentina','international-rugby-league-men','Argentina','#75AADB','#FFFFFF'),
  ('australia','international-rugby-league-men','Australia','#00843D','#FFD700'),
  ('belgium','international-rugby-league-men','Belgium','#ED2939','#000000'),
  ('bosnia-and-herzegovina','international-rugby-league-men','Bosnia and Herzegovina','#002395','#FECB00'),
  ('brazil','international-rugby-league-men','Brazil','#FFDF00','#009739'),
  ('bulgaria','international-rugby-league-men','Bulgaria','#FFFFFF','#00966E'),
  ('cameroon','international-rugby-league-men','Cameroon','#009739','#FCD116'),
  ('canada','international-rugby-league-men','Canada','#FF0000','#FFFFFF'),
  ('chile','international-rugby-league-men','Chile','#D52B1E','#FFFFFF'),
  ('colombia','international-rugby-league-men','Colombia','#FCD116','#003893'),
  ('cook-islands','international-rugby-league-men','Cook Islands','#00247D','#FFFFFF'),
  ('czech-republic','international-rugby-league-men','Czech Republic','#D7141A','#11457E'),
  ('denmark','international-rugby-league-men','Denmark','#C60C30','#FFFFFF'),
  ('ecuador','international-rugby-league-men','Ecuador','#FFD100','#034EA2'),
  ('el-salvador','international-rugby-league-men','El Salvador','#0047AB','#FFFFFF'),
  ('england','international-rugby-league-men','England','#FFFFFF','#CF081F'),
  ('fiji','international-rugby-league-men','Fiji','#71C5E8','#FFFFFF'),
  ('france','international-rugby-league-men','France','#002654','#FFFFFF'),
  ('germany','international-rugby-league-men','Germany','#FFFFFF','#000000'),
  ('ghana','international-rugby-league-men','Ghana','#FCD116','#006B3F'),
  ('greece','international-rugby-league-men','Greece','#0D5EAF','#FFFFFF'),
  ('hong-kong','international-rugby-league-men','Hong Kong','#DE2910','#FFFFFF'),
  ('hungary','international-rugby-league-men','Hungary','#CD2A3E','#436F4D'),
  ('india','international-rugby-league-men','India','#0033A0','#FF671F'),
  ('ireland','international-rugby-league-men','Ireland','#169B62','#FFFFFF'),
  ('italy','international-rugby-league-men','Italy','#0F4C81','#FFFFFF'),
  ('jamaica','international-rugby-league-men','Jamaica','#FED100','#009B3A'),
  ('japan','international-rugby-league-men','Japan','#BC002D','#FFFFFF'),
  ('kenya','international-rugby-league-men','Kenya','#006400','#CE1126'),
  ('lebanon','international-rugby-league-men','Lebanon','#ED1C24','#00A651'),
  ('lithuania','international-rugby-league-men','Lithuania','#FDB913','#006A44'),
  ('macedonia','international-rugby-league-men','Macedonia','#D20000','#FFE600'),
  ('malta','international-rugby-league-men','Malta','#CE1126','#FFFFFF'),
  ('mexico','international-rugby-league-men','Mexico','#006847','#FFFFFF'),
  ('moldova','international-rugby-league-men','Moldova','#0033A0','#FFD200'),
  ('montenegro','international-rugby-league-men','Montenegro','#C40308','#D4AF37'),
  ('morocco','international-rugby-league-men','Morocco','#C1272D','#006233'),
  ('netherlands','international-rugby-league-men','Netherlands','#FF6C00','#FFFFFF'),
  ('new-zealand','international-rugby-league-men','New Zealand','#000000','#FFFFFF'),
  ('nicaragua','international-rugby-league-men','Nicaragua','#0067C6','#FFFFFF'),
  ('nigeria','international-rugby-league-men','Nigeria','#008751','#FFFFFF'),
  ('niue','international-rugby-league-men','Niue','#FFD700','#00247D'),
  ('norway','international-rugby-league-men','Norway','#BA0C2F','#00205B'),
  ('pakistan','international-rugby-league-men','Pakistan','#01411C','#FFFFFF'),
  ('papua-new-guinea','international-rugby-league-men','Papua New Guinea','#CE1126','#000000'),
  ('peru','international-rugby-league-men','Peru','#D91023','#FFFFFF'),
  ('philippines','international-rugby-league-men','Philippines','#0038A8','#CE1126'),
  ('poland','international-rugby-league-men','Poland','#DC143C','#FFFFFF'),
  ('portugal','international-rugby-league-men','Portugal','#FF0000','#046A38'),
  ('puerto-rico','international-rugby-league-men','Puerto Rico','#DA121A','#0033A0'),
  ('russia','international-rugby-league-men','Russia','#FFFFFF','#D52B1E'),
  ('samoa','international-rugby-league-men','Samoa','#002B7F','#CE1126'),
  ('scotland','international-rugby-league-men','Scotland','#00205B','#FFFFFF'),
  ('serbia','international-rugby-league-men','Serbia','#C6363C','#0C4076'),
  ('singapore','international-rugby-league-men','Singapore','#EF3340','#FFFFFF'),
  ('slovakia','international-rugby-league-men','Slovakia','#0B4EA2','#EE1C25'),
  ('solomon-islands','international-rugby-league-men','Solomon Islands','#0051BA','#FCD116'),
  ('south-africa','international-rugby-league-men','South Africa','#007A4D','#FFB612'),
  ('south-sudan','international-rugby-league-men','South Sudan','#000000','#DA121A'),
  ('spain','international-rugby-league-men','Spain','#C60B1E','#FFC400'),
  ('sudan','international-rugby-league-men','Sudan','#D21034','#000000'),
  ('sweden','international-rugby-league-men','Sweden','#006AA7','#FECC02'),
  ('thailand','international-rugby-league-men','Thailand','#A51931','#2D2A4A'),
  ('tonga','international-rugby-league-men','Tonga','#C10000','#FFFFFF'),
  ('turkey','international-rugby-league-men','Turkey','#E30A17','#FFFFFF'),
  ('ukraine','international-rugby-league-men','Ukraine','#005BBB','#FFD500'),
  ('uruguay','international-rugby-league-men','Uruguay','#6CACE4','#FFFFFF'),
  ('usa','international-rugby-league-men','USA','#002868','#BF0D3E'),
  ('vanuatu','international-rugby-league-men','Vanuatu','#CE1126','#009543'),
  ('vietnam','international-rugby-league-men','Vietnam','#DA251D','#FFCD00'),
  ('wales','international-rugby-league-men','Wales','#C8102E','#FFFFFF'),
  ('west-indies','international-rugby-league-men','West Indies','#7B1113','#FFD700')
on conflict (competition_slug, slug) do update
  set primary_color = excluded.primary_color, secondary_color = excluded.secondary_color;
